redmine_app_port: "8080"
redmine_version: "5.0.0"
redmine_env_dir: "/etc/redmine"

pip_install_packages:
  - name: docker
  
datadog_api_key: "{{ vault_datadog_api_key }}"
datadog_site: "datadoghq.com"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: Application health check status
        url: "http://localhost:{{ redmine_app_port }}"
        timeout: 5
        method: GET
