- hosts: all
  become: true

  pre_tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: true

  roles:
    - role: geerlingguy.pip

  tasks:
    - name: make .env file from template
      ansible.builtin.template:
        src: ./templates/redmine.env.j2
        dest: /etc/.env
        mode: '0600'

    - name: start redmine docker image
      community.docker.docker_container:
        name: devops-example-app
        image: redmine
        published_ports: "{{ app_port }}:3000"
        restart_policy: always
        restart: true
        container_default_behavior: no_defaults
        pull: true
        env_file:
          /etc/.env

- hosts: webservers
  become: true

  roles:
    - name: datadog.datadog
